### ISSUE TITLE
Update crates

### ISSUE THREAD

**Issue by nasifimtiazohi** [diem/whackadep#52]
- [x] tokio
- [x] guppy
- [ ] rocket (#54)
- [ ] rust toolchain

1. If `cargo update` updates a crate to its latest version, e.g., `tokio 1.2.0 -> 1.6.1`, do I also need to change that in the `Cargo.toml` files?
2. Does updating tokio mean updating all `tokio` related crates. e.g., `tokio-macros`, `tokio-native-tls` etc?

@bmwill

**Comment by bmwill** [comment]
1) Yes lets also update the Cargo.toml files as well as the lock files.
2) No you should only have to upgrade the tokio crate

**Comment by nasifimtiazohi** [comment]
How should I approach updating `guppy` and `guppy-summaries` ?

https://github.com/diem/whackadep/blob/bae00c888ed0ba9e2179966990b203da34c14dab/web-backend/metrics/Cargo.toml#L26-L27

replace them with `cargo-guppy` ? @bmwill

**Comment by bmwill** [comment]
`cargo-guppy` is a binary tool, here we're interested in actually updating the libraries. so guppy should be updated to v0.9 and guppy-summaries to v0.4

**Comment by nasifimtiazohi** [comment]
changing rocket framework.
