### ISSUE TITLE
[deps] Rocket-contrib has been split into distinct crates

### ISSUE THREAD

**Issue by nasifimtiazohi** [diem/whackadep#54]
In the latest master, `rocket-contrib` has been split into distinct crate. See [issue](https://github.com/SergioBenitez/Rocket/commit/5a4e66ec439411d30f16e5c045f8e4986f5883a4).

Apparently, it was split into `rocket_sync_db_pools` and `rocket_dyn_templates`.

However these contain some breaking change:

1. We use `rocket_contrib` only once here: https://github.com/diem/whackadep/blob/bae00c888ed0ba9e2179966990b203da34c14dab/web-backend/ui/src/main.rs#L11
[the json wrapper seems to be removed](https://github.com/SergioBenitez/Rocket/commit/c74bcfd40a47b35330db6cafb88e4f3da83e0d17#diff-8ad971f648ba25fb55b85ca9eca58ee5ba56c29671a0c5bfe88140d9690b8d27)
2. `compile_error!("at least one of \"tera\" or \"handlebars\" features must be enabled");` as specified in the above mentioned issue. 

@bmwill What should we do?

**Comment by bmwill** [comment]
We've migrated to using warp instead of rocket so this isn't an issue now
